name: Deploy to Master

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Master
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Master Environment
        run: echo "Deploying to Master Environment..."

      - name: Delete Branch
        run: git push --delete origin ${{ github.event.pull_request.head.ref }}
